@startuml
title: Server architecture
allowmixing

skinparam rectangle {
	BackgroundColor #f5f5f5
	BorderColor #42b983
}

skinparam database {
	BackgroundColor #f5f5f5
	BorderColor #09ABF6
}


skinparam folder {
	BackgroundColor #f5f5f5
	BorderColor #F5A623
}

skinparam file {
	BackgroundColor #f5f5f5
	BorderColor #F5A623
}
skinparam storage {
	BackgroundColor #f5f5f5
	BorderColor #09ABF6
}
skinparam actor {
	BackgroundColor #f3f3f3
	BorderColor #ff6699
}

skinparam class {
	ArrowColor #8d7edc
}


actor Studetns
actor Staff

node "Host Machine"  {
    node "Nginx Server Container" {
        rectangle Nginx
    }
    node "Application Container" {
        rectangle uWSGI
        rectangle "Django App"
    }
    node "Database Container" {
        database "PostgreSQL database"
    }
    folder "Static Files"
    folder "Shared Files"
    file "Unix Socket"
    file "uWSGI log"
    storage "Data Volume"

}

Nginx --> Studetns
Nginx --> Staff

"uWSGI log" <-- uWSGI


"Django App" <--> "PostgreSQL database"

"Django App" <-left-> uWSGI
"Django App" <--> uWSGI
"Django App" <--> uWSGI

"Unix Socket" <--> uWSGI
"Unix Socket" <--> Nginx

"Static Files" -up-> Nginx
"Shared Files" -up-> Nginx

"PostgreSQL database" <--> "Data Volume"


@enduml